-- liquibase formatted sql

-- changeset prokhorovamv:1
CREATE TABLE users
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name  VARCHAR(16) NOT NULL,
    last_name   VARCHAR(16) NOT NULL,
    email       VARCHAR(32) NOT NULL,
    password    VARCHAR(16) NOT NULL,
    phone       VARCHAR(12) NOT NULL,
    role        VARCHAR,
    image       TEXT
);

-- changeset prokhorovamv:2
CREATE TABLE ads
(
    pk           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR(32) NOT NULL,
    price        INTEGER NOT NULL,
    description  VARCHAR(64) NOT NULL,
    image        TEXT,
    users_id     INTEGER,

        CONSTRAINT fk_ads_users
            FOREIGN KEY (users_id) REFERENCES users (id) ON DELETE CASCADE
);

-- changeset prokhorovamv:3
CREATE TABLE comments
(
    pk           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text         VARCHAR(64) NOT NULL,
    data_time   BIGINT NOT NULL,

    users_id     INTEGER,
           CONSTRAINT fk_comments_user
           FOREIGN KEY (users_id) REFERENCES users (id) ON DELETE CASCADE,

    ads_pk       INTEGER,
           CONSTRAINT fk_comments_ads
           FOREIGN KEY (ads_pk) REFERENCES ads (pk) ON DELETE CASCADE

);
